window.FORMER_STUDENTS = [
  {
    id: "project-imperfect-student-sim",
    year: "2025",
    types: "Text",
    mediaHref: "../assets/teaching/current-students/img-002-8fba22da5d.png",
    imgSrc: "../assets/teaching/current-students/img-002-8fba22da5d.png",
    imgAlt: "Imperfect Student Simulations project image",
    title: "Imperfect Student Simulations using LLMs",
    meta: "Omri Sasson \u00b7 2025",
    tags: ["Text"],
    text: "Imperfect student simulations with LLMs to model realistic misunderstandings and learning gaps.",
    links: []
  },
  {
    id: "project-dewarping-diffusion",
    year: "2025",
    types: "Images",
    mediaHref: "../assets/teaching/former-students/img-013-6b76b0cb0b.png",
    imgSrc: "../assets/teaching/former-students/img-013-6b76b0cb0b.png",
    imgAlt: "Diffusion de-warping project image",
    title: "Extreme image de-warping using diffusion models",
    meta: "Igor Adamenko, Orpaz Ben-Aharon \u00b7 2025",
    tags: ["Images"],
    text: "Explored diffusion-based de-warping for images with severe geometric distortion. Iterative restoration recovered structure and detail beyond traditional correction pipelines.",
    links: []
  },
  {
    id: "project-graph-photo-tagging",
    year: "2025",
    types: "Images,Graphs",
    mediaHref: "../assets/teaching/former-students/img-014-a233207a84.png",
    imgSrc: "../assets/teaching/former-students/img-014-a233207a84.png",
    imgAlt: "Graph-based photo tagging project image",
    title: "Photo tagging via graph knowledge propagation",
    meta: "Adir Cohen \u00b7 2025",
    tags: ["Images", "Graphs"],
    text: "Implemented graph-based label propagation over image-similarity networks for large photo sets. The method improved tag consistency when individual images had weak local evidence.",
    links: []
  },
  {
    id: "project-active-vision-aerial",
    year: "2025",
    types: "Images,Video",
    mediaHref: "../assets/teaching/former-students/img-015-0a721d5c1c.png",
    imgSrc: "../assets/teaching/former-students/img-015-0a721d5c1c.png",
    imgAlt: "Active vision for aerial imaging project image",
    title: "Active vision for aerial imaging",
    meta: "Yuri Liziakin \u00b7 2025",
    tags: ["Images", "Video"],
    text: "Designed an active-vision pipeline that scans scenes coarsely, then captures high-value regions at high resolution. This reduced bandwidth while preserving captioning and scene-understanding quality.",
    links: []
  },
  {
    id: "project-dark-image-classification",
    year: "2024",
    types: "Images",
    mediaHref: "../assets/teaching/former-students/img-011-f7150cb871.png",
    imgSrc: "../assets/teaching/former-students/img-011-f7150cb871.png",
    imgAlt: "Dark image classification project image",
    title: "Classification of dark images",
    meta: "Rom Hirsch, Yarom Swisa \u00b7 2024",
    tags: ["Images"],
    text: "Built a classifier tuned for low-light imagery with illumination-aware preprocessing and robust feature extraction. It improved recognition on dark, noisy, and low-contrast scenes.",
    links: []
  },
  {
    id: "project-audio-alarms",
    year: "2024",
    types: "Audio",
    mediaHref: "../assets/teaching/former-students/img-012-4f5caf5322.png",
    imgSrc: "../assets/teaching/former-students/img-012-4f5caf5322.png",
    imgAlt: "Audio alarm detection project image",
    title: "Audio alarm detection",
    meta: "Ben Kedarya, Yael Rikka \u00b7 2024",
    tags: ["Audio"],
    text: "Developed real-time alarm detection for critical sounds such as fire alarms and doorbells. The system supports visual or haptic alerts for hearing-impaired users.",
    links: []
  },
  {
    id: "project-dashboard-controls",
    year: "2023",
    types: "Images",
    mediaHref: "../assets/teaching/former-students/img-009-d7875b19b4.png",
    imgSrc: "../assets/teaching/former-students/img-009-d7875b19b4.png",
    imgAlt: "Vehicle dashboard control recognition project image",
    title: "Recognition of control elements in vehicle dashboards",
    meta: "Eyal Reis \u00b7 2023",
    tags: ["Images"],
    text: "Developed a vision system that detects and classifies dashboard controls, indicators, and display elements. The solution supports reliable mapping of in-cabin interfaces for assistive and testing workflows.",
    links: []
  },
  {
    id: "project-haze-detection",
    year: "2023",
    types: "Images",
    mediaHref: "../assets/teaching/former-students/img-010-e36e90531b.png",
    imgSrc: "../assets/teaching/former-students/img-010-e36e90531b.png",
    imgAlt: "Haze-aware object detection project image",
    title: "Haze-aware object detection",
    meta: "Aharon Sahalulu \u00b7 2023",
    tags: ["Images"],
    text: "Developed a haze-aware detector that compensates for visibility loss in foggy scenes. Preprocessing and robustness training improved detection consistency under adverse weather.",
    links: []
  },
  {
    id: "project-slam-mosaicking",
    year: "2021",
    types: "Images,Video",
    mediaHref: "../assets/teaching/former-students/img-007-ed6bd945b7.png",
    imgSrc: "../assets/teaching/former-students/img-007-ed6bd945b7.png",
    imgAlt: "SLAM image mosaicking project image",
    title: "Image mosaicking using SLAM techniques",
    meta: "Inga Efrosman, Daniel Cohen \u00b7 2021",
    tags: ["Images", "Video"],
    text: "Implemented image mosaicking with SLAM-based camera tracking to build large panoramas from overlapping views. The method reduced drift and improved alignment on long sequences.",
    links: [{ label: "Report", href: "https://arxiv.org/pdf/2509.04370?" }]
  },
  {
    id: "project-interjection-speech",
    year: "2021",
    types: "Audio,Text",
    mediaHref: "../assets/teaching/former-students/img-008-b0e61fc8ca.png",
    imgSrc: "../assets/teaching/former-students/img-008-b0e61fc8ca.png",
    imgAlt: "Interjection speech recognition project image",
    title: "Interjection Speech Recognition",
    meta: "Yaniv Goren \u00b7 2021",
    tags: ["Audio", "Text"],
    text: "Built a speech interface focused on short interjections such as \u201chmm\u201d and \u201cuh-huh.\u201d The model improved recognition of quick conversational signals in noisy settings.",
    links: [{ label: "Report", href: "https://arxiv.org/pdf/2509.03181?" }]
  },
  {
    id: "project-selective-inferencing",
    year: "2020",
    types: "Images,Signals",
    mediaHref: "../assets/teaching/former-students/img-005-540d1ead48.png",
    imgSrc: "../assets/teaching/former-students/img-005-540d1ead48.png",
    imgAlt: "Selective inferencing project image",
    title: "Deep learning model optimization via selective inferencing",
    meta: "Yael Galifat \u00b7 2020",
    tags: ["Images", "Signals"],
    text: "Explored selective inference strategies that route uncertain samples to heavier deep models. This reduced average compute cost while preserving target accuracy.",
    links: []
  },
  {
    id: "project-egocentric-interactions",
    year: "2020",
    types: "Video,Images",
    mediaHref: "../assets/teaching/former-students/img-006-0b586accc7.png",
    imgSrc: "../assets/teaching/former-students/img-006-0b586accc7.png",
    imgAlt: "Egocentric interaction detection project image",
    title: "Detection of human interactions in egocentric video",
    meta: "Barak Katz \u00b7 2020",
    tags: ["Video", "Images"],
    text: "Designed a first-person video model for recognizing human interactions in egocentric scenes. Temporal cues and viewpoint-aware features improved robustness in daily-life recordings.",
    links: []
  },
  {
    id: "project-curriculum-learning",
    year: "2019",
    types: "Images",
    mediaHref: "../assets/teaching/former-students/img-004-d5d95f6c14.png",
    imgSrc: "../assets/teaching/former-students/img-004-d5d95f6c14.png",
    imgAlt: "Curriculum learning project image",
    title: "Curriculum learning for image classification",
    meta: "Dan Basson \u00b7 2019",
    tags: ["Images"],
    text: "Evaluated curriculum learning schedules by ordering training samples from easier to harder. The approach stabilized optimization and improved performance under limited training budgets.",
    links: []
  },
  {
    id: "project-segmentation-super-resolution",
    year: "2018",
    types: "Images",
    mediaHref: "../assets/teaching/former-students/img-003-54fd954ea5.png",
    imgSrc: "../assets/teaching/former-students/img-003-54fd954ea5.png",
    imgAlt: "Joint segmentation and super-resolution project image",
    title: "Joint segmentation and super resolution",
    meta: "Ran Mishael \u00b7 2018",
    tags: ["Images"],
    text: "Developed a model that performs segmentation and super-resolution in one pass. Shared features across tasks improved boundary quality and detail recovery on low-resolution images.",
    links: []
  },
  {
    id: "project-3d-root-monitoring",
    year: "2013",
    types: "Images",
    mediaHref: "../assets/teaching/former-students/img-001-dc8c377457-9c834a0e21.png",
    imgSrc: "../assets/teaching/former-students/img-001-dc8c377457-9c834a0e21.png",
    imgAlt: "3D root monitoring project image",
    title: "3D Vision for vegetation root monitoring",
    meta: "Ozi Marom \u00b7 2013",
    tags: ["Images"],
    text: "Built a stereo imaging setup to capture synchronized plant views and reconstruct root structures in 3D. The system enabled non-destructive monitoring of root morphology and growth over time.",
    links: []
  },
  {
    id: "project-bookmark-tagging",
    year: "2013",
    types: "Text",
    mediaHref: "../assets/teaching/former-students/img-002-c2afa9aa60.png",
    imgSrc: "../assets/teaching/former-students/img-002-c2afa9aa60.png",
    imgAlt: "Automatic bookmark tagging project image",
    title: "Automatic tagging of browser bookmarks",
    meta: "Alex Gusin \u00b7 2013",
    tags: ["Text"],
    text: "Built a bookmark tagging pipeline that analyzes page text and metadata to assign tags automatically. This improved organization and retrieval without manual labeling.",
    links: []
  }
];
